### ISSUE TITLE
Fit to screen有効時にPointEventの座標が正しくない

### ISSUE THREAD

**Issue by pkpkTech** [akashic-games/akashic-cli#1075]
`akashic serve` コマンドでゲームの動作確認を行う際に、Display Optionsの"Fit to screen"を有効にしてゲームの表示スケールを変更している状態だと、エンティティ等をタッチした時のPointEventから得られる座標がズレています。
得られる座標はスケールを無視していて、例えば解像度1280*720のゲームを半分のスケールで表示した場合、ゲームの一番右下をタッチすると` { x:640, y:360 } `になっています。

**Comment by xnv** [comment]
ありがとうございます。現象を確認できました。対応します。

**Comment by xnv** [comment]
akashic-cli@2.15.67 で修正を publish しました。
