### ISSUE TITLE
[提案] serve時に"Fit to screen"などの設定をできるようにして欲しい

### ISSUE THREAD

**Issue by Negima1072** [akashic-games/akashic-cli#1132]
マルチプレイゲームを開発する際、複数インスタンスでの同時動作確認が求められる場合がある。
その際、既存では画面サイズのウィンドウが複数表示され、いちいち大きさを変え"Fit to screen"を有効にしないと一画面上で作業することが難しい。このようなゲーム開発者に向け以下の機能の追加を提案したい。

- `akashic serve`のオプション、もしくは`sandbox.config.js`にて、`--fit-to-screen`の追加
- 同様に開かれるブラウザのwidth,heightの指定

**Comment by xnv** [comment]
ありがとうございます。  sandbox.config.js で表示オプションのデフォルト値を指定できるのはよさそうですね。検討します。

**Comment by xnv** [comment]
間が空いてしまいましたが、 #1147, #1157 で「sandbox.config.js で serve の Display Options の初期値などを指定可能にする」対応を行いました。以下のような記述が可能になっています。

```javascript
module.exports = { 

  // serve でウィンドウを開いた時の "Display Options" の初期値
  displayOptions: {
    fitsToScreen: true
  },

  // serve でウィンドウを開いた時のサイズ
  windowSize: {
    width: 640,
    height: 400 
  }
  
  // (その他の記述)
  // ...
};
```

記述できる値の詳細は、ひとまずソースコードのコメントですが [こちら](https://github.com/akashic-games/sandbox-configuration/blob/main/src/SandboxConfiguration.ts#L76-L112) にまとまっています。

akashic-cli@2.15.82 から利用できますのでご確認いただければと思います。

**Comment by Negima1072** [comment]
ご対応ありがとうございます！！
有り難く活用させていただきますm(_ _)m
問題は解決したと思うのでcloseさせていただきます。
