### ISSUE TITLE
akashic exportに時間が掛かる

### ISSUE THREAD

**Issue by mujurin1** [akashic-games/akashic-cli#1244]
磯辺焼きさんの[ブログ](https://isobe-yaki.hateblo.jp/entry/2023/06/02/021809)で書いている内容を元に書いています

akashic exportコマンドを実行した際に、エクスポートが完了するまでに掛かる時間がとても長いです
エクスポートする際にプロジェクトフォルダ内の全てのファイルをコピーしているのが原因のようです
必要なファイルのみコピーするようにして欲しいです

場合によってはAkashicEngineは関与しないけどビルドに必要なファイルもある可能性があるため、コピーするフォルダ/ファイルを指定する方法も必要かもしれないです

**Comment by xnv** [comment]
ありがとうございます。ゲームに必要なファイルは game.json から確定できるはずなので、必要なファイルだけコピーするのが良さそうですね。

一方で、akashic export は「ゲームを公開する際」のファイルを生成するコマンドなので、その目的の限りでは「ビルドに必要なだけのファイル」は含めなくてよいかと考えています。もしそれが欲しいケース (＝export した結果をさらにビルドする (？)) があればご指摘いただきたいです。

**Comment by mujurin1** [comment]
そうですね。既にビルドされたファイルから生成するならビルドに必要なファイルは含める必要は無いですね
game.jsonで書いている他にファイルを含める操作が必要になることはなさそうです
