### ISSUE TITLE
akashic stat sizeが"vector-image", "binary"アセットに対応していない

### ISSUE THREAD

**Issue by pkpkTech** [akashic-games/akashic-cli#1358]
game.json の assets に type が "vector-image" もしくは "binary" のアセットがに含まれていると `akashic stat size` を実行したときに 
```
Error: vector-image is not a valid asset type name
```
と表示されてサイズの確認ができません。

**Comment by xnv** [comment]
ありがとうございます。修正を取り込んで akashic-cli@2.1.76 で publish しました。
