### ISSUE TITLE
akachi-cliと依存するモジュールのtypingsが古い

### ISSUE THREAD

**Issue by kamakiri01** [akashic-games/akashic-cli#3]
`npm install` 実行時に、typingsからWARNが出力されます。stableなバージョンや代替に更新したいです。
これらakashic-cli以下の依存モジュールは同じtypingsへの参照を持っている物があるので、同時に更新作業したいです。

**Comment by xnv** [comment]
lerna 移行以前の issue のはず。 もはや typings を使っていないので close します。
