### ISSUE TITLE
音声ファイルへの警告の矛盾

### ISSUE THREAD

**Issue by pkpkTech** [akashic-games/akashic-cli#671]
`akashic stat size` コマンドを使用した時に、拡張子が`.aac`の音声ファイルが含まれていると以下の警告が表示されます。

> `WARN: AAC (.aac) is deprecated. Use MP4(AAC) (.mp4) instead.`

この警告に従ってMP4(AAC)な拡張子`.mp4`の音声ファイルに差し替えると同コマンドでは警告がでなくなりますが、この状態で`akashic scan asset`コマンドを使用した時には以下のように真逆の警告が表示されます。

> `WARN: [deprecated] *.mp4 uses deprecated format. Use AAC instead of MP4(AAC).`

[公式のチュートリアル](https://akashic-games.github.io/tutorial/v3/audio.html)に従うならば`.aac`ファイルを使用する方が正しいと思いますが、どちらの警告が現在の仕様に沿っているのでしょうか？

**Comment by xnv** [comment]
うっ……ありがとうございます。結論から言えば、チュートリアルと `akashic scan` の警告が正しいです。 (`.mp4` と `.ogg` の組み合わせだと、 Safari での再生に何がしかトラブルがあったように記憶しています)

Akashic Engine が利用する音声ファイルの形式は、各種ブラウザの仕様・動作の影響で何度か変更を余儀なくされており、特に拡張子 `.aac` の扱いは二転三転しています。 `akashic stat` の間違った警告は、その変更に際しての追従漏れかと思います。 `stat` の不具合として修正します。

**Comment by ShinobuTakahashi** [comment]
#685 で対応済みのためクローズします
