### ISSUE TITLE
古いd.tsを更新する

### ISSUE THREAD

**Issue by kamakiri01** [akashic-games/akashic-cli#8]
typingsからdeprecated指定されている型定義を利用しているので、インストール時に警告が出ます。
バージョンの更新や@typesへの移行を検討したいです。
akashic-cli-XXXはどれも概ね同じ型定義ファイルを利用しているので、一斉に更新できることが望ましいと思います。

**Comment by xnv** [comment]
typings 廃止完了済みのため close します。
